---
title: "QMD3 Solution"
author: "Husnain Mustafa"
date: today
format:
  html: default
execute:
  echo: false
  warning: false
theme: darkly

---

```{python}
#| tags: [parameters]

season_no=1
```

```{python}
import pandas as pd

# Load the data using Python's pandas
season_data = pd.read_csv(f"../../Data/got/season_{season_no}.csv")

def extract_and_convert_date(date_string):
    # Extract the part within parentheses
    date_part = date_string.split('(')[-1].strip(')')
    # Convert to datetime
    return pd.to_datetime(date_part, errors='coerce')

# Apply the function to the premiere_date column
season_data['premiere_date'] = season_data['premiere_date'].apply(extract_and_convert_date)


```

# Game of Thrones - Season `{python} season_no` Summary in Numbers

### __(*Warning:* spoilers ahead)__

***

### Overview

(From the [Wikipedia](https://en.wikipedia.org/wiki/Game_of_Thrones#Premise)) Game of Thrones is an American fantasy drama television series created by David Benioff and D. B. Weiss for HBO. It is an adaptation of A Song of Ice and Fire, a series of fantasy novels by George R. R. Martin, the first of which is A Game of Thrones.

Set on the fictional continents of Westeros and Essos, Game of Thrones has a large ensemble cast and follows several story arcs throughout the course of the show. A major arc concerns the Iron Throne of the Seven Kingdoms of Westeros through a web of political conflicts among the noble families either vying to claim the throne or fighting for independence from it. Another focuses on the last descendant of the realm's deposed ruling dynasty, who has been exiled to Essos and is plotting a return to the throne. A third story arc follows the Night's Watch, a military order defending the realm against threats from the North.
***


### Season `{python} season_no` Summary

```{python}
# Summary statistics for the season
episodes_no = len(season_data)
date_start = season_data['premiere_date'].iloc[0].strftime('%B %d, %Y')  
date_end = season_data['premiere_date'].iloc[-1].strftime('%B %d, %Y')    


viewers = round(season_data['viewers'].mean(),2)
viewers_start = season_data['viewers'].iloc[0]
viewers_end = season_data['viewers'].iloc[-1]

max_viewers = season_data['viewers'].max()
top_episode_desc = season_data.loc[season_data['viewers'] == max_viewers, 'description'].values[0]

```

Season `{python} season_no` of Game of Thrones consisted of `{python} episodes_no` episodes that aired between `{python} date_start` and `{python} date_end` on HBO. The show gathered an average of `{python} viewers` first-day TV viewers in the US, with the number growing from `{python} viewers_start` to `{python} viewers_end` million by the end of the season.

The most popular episode of the season was "Fire and Blood", in which:

> `{python} top_episode_desc`

***

You can see how the viewership of the episodes changed in Figure 1.

```{python}
#| label: "viewers_plot"
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.plot(season_data['viewers'], color='red', linewidth=5)
plt.xlabel('Episode number')
plt.ylabel('1st day TV viewers in the US (millions)')
plt.title(f'Viewership of Game of Thrones Season {season_no}')
plt.show()
```
***



Finally, the episodes with the above-average viewership were:

```{python}
season_data = season_data.rename(columns={'no_season': 'episode_no'})
above_average_episodes = season_data[season_data['viewers'] > viewers]
above_average_episodes[['episode_no', 'title', 'directed_by']]
```